name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/checkout@v3
    - name: Setup environment
      run: pip install Cython buildozer kivy kivymd
    #    pip install -e .

    #- run: buildozer --help
    #- run: buildozer init
    - name: SDK, NDK and p4a download
      run: |
        sed -i.bak "s/#p4a.branch = master/p4a.branch = develop/" buildozer.spec
        buildozer android p4a -- --help
    # Install OS specific dependencies
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt -y install automake default-jre default-jdk

    - name: buildozer android debug
      run: |
        touch main.py
        buildozer android debug
   # - name: buildozer android release
   #   env:
   #     BUILDOZER_ALLOW_KIVY_ORG_DOMAIN: 1 # export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
  #    run: |
    #    touch main.py
    #    buildozer android release

